"""Range-testing defaults."""

TEST_SYMBOLS = ("CL", "CO", "CL-CO")
DEFAULT_SYMBOL = "CL"
WINDOW_DAYS = 400
DEFAULT_MODE = "extrema"
DEFAULT_PEAK_LOOKBACK = 10
DEFAULT_PEAK_RANK = 3
DEFAULT_VALLEY_LOOKBACK = 10
DEFAULT_VALLEY_RANK = 3
DEFAULT_MAX_PARALLEL_POSITIONS = 8
DEFAULT_MAX_CONSECUTIVE_DIRECTION = 4
DEFAULT_NO_TRADE_DAYS = 80
DEFAULT_MAX_TRADE_DAYS = 400
SWING_DIFFERENCE_LOOKBACK = 25
SWING_DIFFERENCE_TOP_COUNT = 6
DEFAULT_HISTORY_YEARS = 10
