"""Range-testing defaults."""

DEFAULT_SYMBOL = "CL-CO"
WINDOW_DAYS = 400
DEFAULT_MODE = "extrema"
DEFAULT_PEAK_LOOKBACK = 10
DEFAULT_PEAK_RANK = 3
DEFAULT_VALLEY_LOOKBACK = 10
DEFAULT_VALLEY_RANK = 3
DEFAULT_MAX_PARALLEL_POSITIONS = 8
DEFAULT_MAX_CONSECUTIVE_DIRECTION = 4
DEFAULT_NO_TRADE_DAYS = 80
DEFAULT_MAX_TRADE_DAYS = 400
SWING_DIFFERENCE_LOOKBACK = 25
SWING_DIFFERENCE_TOP_COUNT = 6
DEFAULT_HISTORY_YEARS = 10
DEFAULT_Z_SCORE_THRESHOLD = 1.5
DEFAULT_Z_SCORE_LOOKBACK = 20
DEFAULT_RANK_LOOKBACK = 20
DEFAULT_BAND_RANK = 4
DEFAULT_DAYS_BEFORE_EXPIRY = 400
DEFAULT_NO_TRADE_DAYS_BEFORE_EXPIRY = 5
TIMEFRAME_OPTIONS = (30, 60, 240)
DEFAULT_TIMEFRAME_MINUTES = 60
DEFAULT_TP_TICKS = 3
DEFAULT_SL_TICKS = 3
DEFAULT_MIN_TRADE_GAP_CANDLES = 3
DEFAULT_MOVING_AVERAGE_LOOKBACK = 20
